fastqdir: "/storage/scratch01/users/aquevedo/fastq/ewing_cells/ChipSeq_A673_SA2_lane2/"
datadir: "/storage/scratch01/users/aquevedo/ewing_cells_SA2KO_lane2/data/"
resdir: "/storage/scratch01/users/aquevedo/ewing_cells_SA2KO_lane2/res/"
logdir: "/storage/scratch01/users/aquevedo/ewing_cells_SA2KO_lane2/log/"

tableName: "config/table_ewing_SA2KO_chip_lane2.tsv"
regions: "summits" # possible values: summits | genes
mergedRegions: "no" # possible values: yes | no

rules:
    default:
        res:
            threads: 1
            mem_mb: 8000 #in MB
            walltime: 480   
    fastQC:
        res:
            threads: 8   
    fastQScreen:
        res:
            mem_mb: 10000
            threads: 12
    bowtie2:
        res:
            threads: 15
            mem_mb: 10000
    gatk:
        res:
            mem_mb: 4096 #in MB
            walltime: 25
    create_bigWig:
        res:
            mem_mb: 8000
            threads: 30
    macs2:
        res:
            threads: 2
            mem_mb: 6000
            walltime: 30
            species: "hs"
    compute_matrix:
        res:
            threads: 20
            mem_mb: 8000
            walltime: 60

    plot_heatmap:
        res:
            threads: 10
            mem_mb: 4000
            walltime: 30
            kmeans: 8
            cluster_by_protein: "SA2"

