fastqdir: "/storage/scratch01/users/aquevedo/fastq/NIPBL_mouseHepatocytes_GSE93431/"
datadir: "/storage/scratch01/users/aquevedo/mouseHepatocytes_NIPBLko/data/"
resdir: "/storage/scratch01/users/aquevedo/mouseHepatocytes_NIPBLko/res/"
logdir: "/storage/scratch01/users/aquevedo/mouseHepatocytes_NIPBLko/log/"

tableName: "config/table-NIPBLko_mouseHepatocytes-RNAseq.txt"
regions: "summits" # possible values: <summits | genes>
mergedRegions: "no" # possible values: <yes | no>

gtf: "/storage/scratch01/users/aquevedo/dani_files/genes_hg19.gtf"
feature: "exon" ## must appear in column 3 of gtf
id_counts: "gene_id" ## id to sum htseq counts and to appear in countMatrix 1 row
strandness: "no" ## is RNAseq stranded? <yes | no>

rules:
    default:
        res:
            threads: 1
            mem_mb: 8000 #in MB
            walltime: 480   
    fastQC:
        res:
            threads: 8   
    fastQScreen:
        res:
            mem_mb: 10000
            threads: 12
    bowtie2:
        res:
            threads: 15
            mem_mb: 10000
    hisat2:
        res:
            walltime: 300
            threads: 19
            mem_mb: 15000
    gatk:
        res:
            mem_mb: 4096 #in MB
            walltime: 25
    create_bigWig:
        res:
            mem_mb: 8000
            threads: 30
    
    compute_matrix:
        res:
            threads: 20
            mem_mb: 8000
            walltime: 60


