fastqdir: "/data/aquevedo/fastq/AML-p53sh-GSE132245/"
datadir: "/data/aquevedo/projects/AML-p53sh-GSE132245/data/"
resdir: "/data/aquevedo/projects/AML-p53sh-GSE132245/res/"
logdir: "/data/aquevedo/projects/AML-p53sh-GSE132245/log/"

snakedir: "/home/aquevedo/snakemake_workflows/Chip-Seq/"

tableName: "/data/aquevedo/projects/AML-p53sh-GSE132245/AML-p53sh-GSE132245-table.csv"
regions: "summits" # possible values: <summits | genes>
mergedRegions: "no" # possible values: <yes | no>

gtf: "/data/aquevedo/genomes/human/GRCh38/Homo_sapiens.GRCh38.102.gtf"
feature: "exon" ## must appear in column 3 of gtf
id_counts: "gene_id" ## id to sum htseq counts and to appear in countMatrix 1 row
strandness: "no" ## is RNAseq stranded? <yes | no>

rules:
    default:
        res:
            threads: 1
            mem_mb: 8000 #in MB
            walltime: 480   
    fastQC:
        res:
            threads: 8   
    fastQScreen:
        res:
            mem_mb: 10000
            threads: 12
    bowtie2:
        res:
            threads: 15
            mem_mb: 10000
    hisat2:
        res:
            walltime: 300
            threads: 19
            mem_mb: 15000
    gatk:
        res:
            bin: "/data_genome1/SharedSoftware/GATK/gatk-4.1.9.0/gatk"
            mem_mb: 4096 #in MB
            walltime: 25
    create_bigWig:
        res:
            mem_mb: 8000
            threads: 30
    
    compute_matrix:
        res:
            threads: 20
            mem_mb: 8000
            walltime: 60


