fastqdir: "/storage/scratch01/users/aquevedo/fastq"
datadir: "/storage/scratch01/users/aquevedo/snakemakeTest/data"
resdir: "/storage/scratch01/users/aquevedo/snakemakeTest/res"
logdir: "/storage/scratch01/users/aquevedo/snakemakeTest/log"

tableName: "config/table_siNipbl_cluster.tsv"

rules:
    default:
        res:
            threads: 1
            mem: 8000 #in MB
            walltime: 480   
    fastQC:
        res:
            threads: 8   
    fastQScreen:
        res:
            threads: 15
    bowtie2:
        res:
            threads: 20
            mem: 10000
    gatk:
        res:
            mem: 4096 #in MB
            walltime: 15
    create_bigWig:
        res:
            mem: 8000
            threads: 20
    macs2:
        res:
            threads: 15
            mem: 6000
            walltime: 30
    compute_matrix:
        res:
            threads: 20
            mem: 8000
            walltime: 60

