tableName: "/home/aquevedo/snakemake_workflows/test_WGS/table_test_GATK_WXA_mouse.txt"

# Directories must end with "/" !!!!
fastqdir: "/home/aquevedo/snakemake_workflows/test_WGS/"
datadir: "/home/aquevedo/snakemake_workflows/test_WGS/data/"
resdir: "/home/aquevedo/snakemake_workflows/test_WGS/res/"
logdir: "/home/aquevedo/snakemake_workflows/test_WGS/log/"

gatk_folder: "/home/aquevedo/software/gatk-4.2.2.0/"
picard_folder: ""

condadir: "/home/aquevedo/snakemake_workflows/WGS/env/"
tmp_folder: "/home/aquevedo/snakemake_workflows/test_WGS/tmp/"
script_folder: "/home/aquevedo/snakemake_workflows/WGS/scripts/"


rules:
    default:
        res:
            threads: 1
            mem_mb: 8000 #in MB
            walltime: 480   
    fastQC:
        res:
            threads: 8   
    fastQScreen:
        res:
            mem_mb: 10000
            threads: 12
    bowtie2:
        res:
            threads: 18
            mem_mb: 10000
            walltime: 200
    hisat2:
        res:
            threads: 15
            mem_mb: 15000
    gatk:
        res:
            mem_mb: 4096 #in MB
            walltime: 25
    
    create_bigWig:
        res:
            mem_mb: 8000
            threads: 30

