# Directories must end with "/" !!!!
tableName: "/home/aquevedo/projects/test_GATKsnake/table_test_GATK.txt"
condadir: "/home/aquevedo/snakemake_workflows/WGS/env/"

fastqdir: "/data/projects/MB044_gastric_clones/seqs/DNA/MPIPZ_2020-02/"
datadir: "/home/aquevedo/projects/test_GATKsnake/data/"
resdir: "/home/aquevedo/projects/test_GATKsnake/res/"
logdir: "/home/aquevedo/projects/test_GATKsnake/log/"


gatk_folder: "/data_genome1/SharedSoftware/GATK/gatk-4.1.9.0/"
picard_folder: "/data_genome1/SharedSoftware/Picard/"
script_folder: "/home/aquevedo/snakemake_workflows/WGS/scrpits/"

tmp_folder: "/home/aquevedo/projects/test_GATKsnake/data/tmp/"


rules:
    default:
        res:
            threads: 1
            mem_mb: 8192 #in MB
            walltime: 480   
    fastQC:
        res:
            threads: 8   
    fastQScreen:
        res:
            mem_mb: 10000
            threads: 12
    bwa:
        res:
            threads: 15
            mem_mb: 12000
            walltime: 200
    samtools_sort:
        res:
            threads: 6
            mem_mb: 5000
            walltime: 40
    hisat2:
        res:
            threads: 15
            mem_mb: 15000
    gatk:
        res:
            mem_mb: 8192 #in MB
            walltime: 480
    
    create_bigWig:
        res:
            mem_mb: 8000
            threads: 30

